EShop.WEB/Controllers/MManageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using EShop.BLL.DTO;
using EShop.BLL.Services;
using EShop.Common;
using EShop.WEB.Models;
using EShop.WEB.Util;
using Microsoft.AspNet.Identity;

namespace EShop.WEB.Controllers
{
    [AjaxAuthorize]
    [Authorize]
    public class MManageController : BaseController
    {
        private readonly AddressService _addressService;
        private readonly OrderService _orderService;
        //
        // GET: /MManage/
        public MManageController(AddressService addressService, OrderService orderService)
        {
            _addressService = addressService;
            _orderService = orderService;

        }

        public ActionResult Index()
        {
            ViewBag.Archived =
                _orderService.GetUserOrdersByState(User.Identity.GetUserId(), OrderStates.complete, CurrentLanguage,CurrentCurrency)
                    .Count;
            ViewBag.Canceled =
                _orderService.GetUserOrdersByState(User.Identity.GetUserId(), OrderStates.canceled, CurrentLanguage,CurrentCurrency)
                    .Count;
            ViewBag.Active =
                            _orderService.GetUserOrdersByState(User.Identity.GetUserId(), OrderStates.Active, CurrentLanguage,CurrentCurrency)
                                .Count;

            return View();
        }

        public ActionResult AddressBook()
        {
            List<AddressDTO> addresses = _addressService.GetUserAddresses(User.Identity.GetUserId());
            Mapper.Initialize(cfg => cfg.CreateMap<AddressDTO, AddressVM>());
            var vm = Mapper.Map<List<AddressDTO>, List<AddressVM>>(addresses);
            return View(vm);
        }

        public ActionResult EditAddress(long id)
        {
            var addressDto = _addressService.GetAddressById(id);
            Mapper.Initialize(cfg => cfg.CreateMap<AddressDTO, AddressVM>());
            var vm = Mapper.Map<AddressDTO, AddressVM>(addressDto);
            return View(vm);
        }

        [HttpPost]
        public ActionResult EditAddress(AddressVM vm)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(cfg => cfg.CreateMap<AddressVM, AddressDTO>());
                var addressDto = Mapper.Map<AddressVM, AddressDTO>(vm);
                var res = _addressService.EditAddress(vm.Id, addressDto);
                if (res.Succedeed)
                {
                    return RedirectToAction("AddressBook");
                }
                else
                {
                    ModelState.AddModelError(res.Property, res.Message);
                    return View(vm);
                }
            }
            else
            {
                return View(vm);
            }

        }

        public ActionResult DeleteAddress(long id)
        {
            var res = _addressService.RemoveAddress(id);

            return Json(res);
        }

        public ActionResult AddAddress()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAddress(AddressVM vm)
        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(cfg => cfg.CreateMap<AddressVM, AddressDTO>());
                var addressDto = Mapper.Map<AddressVM, AddressDTO>(vm);
                var res = _addressService.AddAddress(User.Identity.GetUserId(), addressDto);
                if (res.Succedeed)
                {
                    return RedirectToAction("AddressBook");
                }
                else
                {
                    ModelState.AddModelError(res.Property, res.Message);
                    return View(vm);
                }
            }
            else
            {
                return View(vm);
            }

        }


        public ActionResult Order(string state)
        {

            List<OrderDTO> orders;

            var st = (OrderStates)Enum.Parse(typeof(OrderStates), state, true);

            orders = _orderService.GetUserOrdersByState(User.Identity.GetUserId(), st, CurrentLanguage,CurrentCurrency);
            switch (st)
            {
                case OrderStates.canceled:
                    ViewBag.State = "الطلبات الملغاة";
                    break;
                case OrderStates.complete:
                    ViewBag.State = "الطلبات المؤرشفة";
                    break;
                default:
                    ViewBag.State = "الطلبات الفعالة";
                    break;
            }


            Mapper.Initialize(cfg => cfg.CreateMap<OrderDTO, OrderVM>());

            var vm = Mapper.Map<List<OrderDTO>, List<OrderVM>>(orders);
            return View(vm);
        }

    }
}

EShop.WEB/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Routing.Constraints;
using System.Web.UI.WebControls;
using AutoMapper;
using EShop.BLL.DTO;
using EShop.BLL.Infrastructure;
using EShop.BLL.Services;
using EShop.WEB.Models;
using Microsoft.AspNet.Identity;

namespace EShop.WEB.Controllers
{
    public class OrderController : BaseController
    {
        private readonly OrderService _orderService;

        public OrderController(OrderService orderService)
        {
            _orderService = orderService;
        }
        //
        // GET: /Order/
        public ActionResult Index(long id)
        {
            OrderDTO orderDto = _orderService.GetOrderById(id,CurrentLanguage,CurrentCurrency);
            Mapper.Initialize(cfg => cfg.CreateMap<OrderItemDTO, OrderItemVM>());
            Mapper.Initialize(cfg => cfg.CreateMap<AddressDTO, AddressVM>());
            Mapper.Initialize(cfg =>cfg.CreateMap<OrderDTO,OrderVM>());
        

            OrderVM vm = Mapper.Map<OrderDTO, OrderVM>(orderDto);

            return View(vm);
        }

        [HttpPost]
        public ActionResult BankConfirm(UserBankInforamtionVM model)

        {
            if (ModelState.IsValid)
            {
                Mapper.Initialize(cfg=>cfg.CreateMap<UserBankInforamtionVM,AddtionalInfoDTO>());
                var dto = Mapper.Map<UserBankInforamtionVM, AddtionalInfoDTO>(model);
                var res = _orderService.AddOrderWithInfo(User.Identity.GetUserId(),Request.UserHostAddress,Request.UserAgent, CurrentLanguage, CurrentCurrency,dto);
              
                if (res.Succedeed)
                {
                    ViewBag.flag = true;
                    ViewBag.data = Url.Action("Index", "Order", new {id = Int64.Parse(res.Property)});
                }
                else
                {
                    ViewBag.flag = false;
                }
            }
            else
            {
                ViewBag.flag = false;
            }
            return PartialView("_AddtionalInformationPartial", model);

        }
        public ActionResult Confirm()
        {
            //var checkout = Session["checkout"] as CheckOutDTO;

            var res = _orderService.AddOrder(User.Identity.GetUserId(),Request.UserHostAddress,Request.UserAgent,CurrentLanguage,CurrentCurrency);

            //if (res.Succedeed)
            //{
            //    //Session["checkout"] = null;
            //    //Session["step"] = null;
                res = new OperationDetails(true,Url.Action("Index","Order", new {id = Int64.Parse(res.Property)}),"");
            //}
            return Json(res);
        }
	}
}

EShop.WEB/Views/MManage/AddAddress.cshtml
@model EShop.WEB.Models.AddressVM

@{
    ViewBag.Title = "اضافة عنوان";
    Layout = "~/Views/Shared/_Manage.cshtml";
}

<h2>اضافة عنوان</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address1, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address1)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PostCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })*@

                <select name="Country" class="form-control">
                    <option value=""> --- Please Select --- </option>
                    <option value="السعودية" selected="selected">السعودية</option>
                </select>
                @Html.ValidationMessageFor(model => model.Country)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })*@
                <select name="City" class="form-control">
                    <option value=""> --- Please Select --- </option>
                    <option value="الرياض">
                        الرياض
                    </option>
                    <option value="مكة">
                        مكة
                    </option>
                    <option value="المدينة المنورة">
                        المدينة المنورة
                    </option>
                    <option value="بريدة">
                        بريدة
                    </option>
                    <option value="تبوك">
                        تبوك
                    </option>
                    <option value="الدمام">
                        الدمام
                    </option>
                    <option value="الاحساء">
                        الاحساء
                    </option>
                    <option value="القطيف">
                        القطيف
                    </option>
                    <option value="خميس مشيط">
                        خميس مشيط
                    </option>
                    <option value="الطائف">
                        الطائف
                    </option>
                    <option value="نجران">
                        نجران
                    </option>
                    <option value="حفر الباطن">
                        حفر الباطن
                    </option>
                    <option value="الجبيل">
                        الجبيل
                    </option>
                    <option value="ضباء">
                        ضباء
                    </option>
                    <option value="الخرج">
                        الخرج
                    </option>
                    <option value="الثقبة">
                        الثقبة
                    </option>
                    <option value="ينبع البحر">
                        ينبع البحر
                    </option>
                    <option value="الخبر">
                        الخبر
                    </option>
                    <option value="عرعر">
                        عرعر
                    </option>
                    <option value="الحوية">
                        الحوية
                    </option>
                    <option value="عنيزة">
                        عنيزة
                    </option>
                    <option value="سكاكا">
                        سكاكا
                    </option>
                    <option value="جيزان">
                        جيزان
                    </option>
                    <option value="القريات">
                        القريات
                    </option>
                    <option value="الظهران">
                        الظهران
                    </option>
                    <option value="الباحة">
                        الباحة
                    </option>
                    <option value="الزلفي">
                        الزلفي
                    </option>
                    <option value="الرس">
                        الرس
                    </option>
                    <option value="وادي الدواسر">
                        وادي الدواسر
                    </option>
                    <option value="بيشه">
                        بيشه
                    </option>
                    <option value="سيهات">
                        سيهات
                    </option>
                    <option value="شروره">
                        شروره
                    </option>
                    <option value="بحره">
                        بحره
                    </option>
                    <option value="تاروت">
                        تاروت
                    </option>
                    <option value=" الدوادمي">
                        الدوادمي
                    </option>
                    <option value="صبياء">
                        صبياء
                    </option>
                    <option value="بيش">
                        بيش
                    </option>
                    <option value="أحد رفيدة">
                        أحد رفيدة
                    </option>
                    <option value="الفريش">
                        الفريش
                    </option>
                    <option value="بارق">
                        بارق
                    </option>
                    <option value="الحوطة">
                        الحوطة
                    </option>
                    <option value="الأفلاج">
                        الأفلاج
                    </option>
                </select>
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.IsDefault)
                @Html.ValidationMessageFor(model => model.IsDefault)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="حفظ" class="btn btn-default" />
                <input type="button" onclick="location.href='@Url.Action("AddressBook")'" value="عودة" class="btn btn-default" />

            </div>
        </div>
    </div>
}

EShop.WEB/Views/MManage/AddressBook.cshtml
@model List<EShop.WEB.Models.AddressVM>
@{
    ViewBag.Title = "دفتر العناوين";
    if (!Request.IsAjaxRequest())
    {
       
        Layout = "~/Views/Shared/_Manage.cshtml";
    }
}
<div id="t">
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach (var address in Model)
            {
                <tr>
                    <td>
                        <p class="text-justified">
                            @address.FirstName<br />
                            @address.LastName<br />
                            @address.Address1<br />
                            @address.Phone<br />
                            @address.City<br />
                            @address.Country<br />
                            @address.PostCode<br />
                        </p>
                    </td>
                    <td class="text-left"><a href="@Url.Action("EditAddress","MManage",new{id=address.Id})" class="btn btn-info editAddress" id="e-@address.Id">تعديل</a> &nbsp;@if (!address.IsDefault)
                                                                                                                                                                                {
                                                                                                                                                                                    <a href="#" onclick="return confirm('تأكيد الحذف ؟');" class="btn btn-danger delete-address" id="d-@address.Id">حذف</a>
                                                                                                                                                                                }</td>
                </tr>
            }
        </tbody>

    </table>
</div>
<div class="buttons clearfix">

    <div class="pull-right"><a href="#" class="btn btn-primary" onclick="location.href = '@Url.Action("AddAddress")';" id="aaa">عنوان جديد</a></div>
</div>
<script>
    $(document).on('click', "a[id*=d-]", function () {
        var iid = $(this).attr('id').substring(2);
        $.ajax({
            type: 'post',
            url: '@Url.Action("DeleteAddress","MManage")',
            data: { id: iid },
            success: function (data) {
                if (data.Succedeed) {

                    alert(data.Message);
                    refresh();
                }
            }
        });
    });
    
</script>
<script>
    function refresh() {
        $.ajax({
            type: 'get',
            url: '@Url.Action("AddressBook","MManage")',
            success: function (data) {
                $('#t').html($(data).find('#t').html());
            }
        });

    }
</script>

EShop.WEB/Views/MManage/EditAddress.cshtml
@model EShop.WEB.Models.AddressVM

@{
    ViewBag.Title = "تعديل عنوان";
    Layout = "~/Views/Shared/_Manage.cshtml";
}
<style>
    label {
        text-align: right !important;
    }
</style>
<hgroup>
    
    <h2>تعديل عنوان</h2>
    @if(@Model.IsDefault)
    {
        <h5>العنوان الافتراضي</h5>
    }
</hgroup>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address1, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address1)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PostCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PostCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })*@

                <select name="Country" class="form-control">
                    <option value=""> --- Please Select --- </option>
                    <option value="السعودية" selected="selected">السعودية</option>
                </select>
                @Html.ValidationMessageFor(model => model.Country)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })*@
                <select name="City" class="form-control">
                    <option value=""> --- Please Select --- </option>
                    <option value="الرياض">
                        الرياض
                    </option>
                    <option value="مكة">
                        مكة
                    </option>
                    <option value="المدينة المنورة">
                        المدينة المنورة
                    </option>
                    <option value="بريدة">
                        بريدة
                    </option>
                    <option value="تبوك">
                        تبوك
                    </option>
                    <option value="الدمام">
                        الدمام
                    </option>
                    <option value="الاحساء">
                        الاحساء
                    </option>
                    <option value="القطيف">
                        القطيف
                    </option>
                    <option value="خميس مشيط">
                        خميس مشيط
                    </option>
                    <option value="الطائف">
                        الطائف
                    </option>
                    <option value="نجران">
                        نجران
                    </option>
                    <option value="حفر الباطن">
                        حفر الباطن
                    </option>
                    <option value="الجبيل">
                        الجبيل
                    </option>
                    <option value="ضباء">
                        ضباء
                    </option>
                    <option value="الخرج">
                        الخرج
                    </option>
                    <option value="الثقبة">
                        الثقبة
                    </option>
                    <option value="ينبع البحر">
                        ينبع البحر
                    </option>
                    <option value="الخبر">
                        الخبر
                    </option>
                    <option value="عرعر">
                        عرعر
                    </option>
                    <option value="الحوية">
                        الحوية
                    </option>
                    <option value="عنيزة">
                        عنيزة
                    </option>
                    <option value="سكاكا">
                        سكاكا
                    </option>
                    <option value="جيزان">
                        جيزان
                    </option>
                    <option value="القريات">
                        القريات
                    </option>
                    <option value="الظهران">
                        الظهران
                    </option>
                    <option value="الباحة">
                        الباحة
                    </option>
                    <option value="الزلفي">
                        الزلفي
                    </option>
                    <option value="الرس">
                        الرس
                    </option>
                    <option value="وادي الدواسر">
                        وادي الدواسر
                    </option>
                    <option value="بيشه">
                        بيشه
                    </option>
                    <option value="سيهات">
                        سيهات
                    </option>
                    <option value="شروره">
                        شروره
                    </option>
                    <option value="بحره">
                        بحره
                    </option>
                    <option value="تاروت">
                        تاروت
                    </option>
                    <option value=" الدوادمي">
                        الدوادمي
                    </option>
                    <option value="صبياء">
                        صبياء
                    </option>
                    <option value="بيش">
                        بيش
                    </option>
                    <option value="أحد رفيدة">
                        أحد رفيدة
                    </option>
                    <option value="الفريش">
                        الفريش
                    </option>
                    <option value="بارق">
                        بارق
                    </option>
                    <option value="الحوطة">
                        الحوطة
                    </option>
                    <option value="الأفلاج">
                        الأفلاج
                    </option>
                </select>
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>
        @if (!Model.IsDefault) { 
        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.IsDefault)
                @Html.ValidationMessageFor(model => model.IsDefault)
            </div>
        </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-1">
                <input type="submit" value="حفظ" class="btn btn-default" />

            </div>
            <div class="col-md-1">
                <input type="button" onclick="location.href='@Url.Action("AddressBook")'" value="عودة" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    $(function() {

        $("option").each(function () {
            console.log($(this).html().trim());
            if ($(this).html().trim() == "@Model.City") {
                $(this).attr('selected', 'selected');
            }
        });
    });
</script>

EShop.WEB/Views/MManage/Index.cshtml
@using EShop.Common
@{
    ViewBag.Title = "معلومات الحساب";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Manage.cshtml";
    }
}

<h4>معلومات الحساب</h4>
<hr />
<style>
    .huge {
        font-size: 40px;
        padding: 2px;
    }
    /*Green*/
    .panel-green {
        border-color: dimgrey;
    }

        .panel-green > .panel-heading {
            border-color: dimgrey;
            color: #fff;
            background-color: dimgrey;
        }

        .panel-green > a {
            color: dimgrey;
        }

            .panel-green > a:hover {
                color: #524f4f;
            }
    /*Blue*/
    .panel-Blue {
        border-color: cadetblue;
    }

        .panel-Blue > .panel-heading {
            border-color: cadetblue;
            color: #fff;
            background-color: cadetblue;
        }

        .panel-Blue > a {
            color: cadetblue;
        }

            .panel-Blue > a:hover {
                color: #1a7375;
            }

    /*Blue*/
    .panel-Red {
        border-color: indianred;
    }

        .panel-Red > .panel-heading {
            border-color: indianred;
            color: #fff;
            background-color: indianred;
        }

        .panel-Red > a {
            color: indianred;
        }

            .panel-Red > a:hover {
                color: indianred;
            }
</style>
<div class="row">
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-Blue">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-8">
                        <div class="huge">@ViewBag.Active</div>
                        <div>الطلبات الفعالة</div>
                    </div>
                    <div class="col-xs-2">
                        <i class="fa fa-tasks fa-3x"></i>
                    </div>

                </div>
            </div>
            <a href="@Url.Action("Order", new { state = OrderStates.Active.ToString() })">
                <div class="panel-footer">
                    <span class="pull-right">عرض التفاصيل</span>
                    <span class="pull-left"><i class="fa fa-arrow-circle-left"></i></span>


                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-Red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-8">
                        <div class="huge">@ViewBag.Canceled</div>
                        <div>الطلبات الملغاة</div>
                    </div>
                    <div class="col-xs-2">
                        <i class="fa fa-tasks fa-3x"></i>
                    </div>

                </div>
            </div>
            <a href="@Url.Action("Order",new {state=OrderStates.canceled.ToString()})">
                <div class="panel-footer">
                    <span class="pull-right">عرض التفاصيل</span>
                    <span class="pull-left"><i class="fa fa-arrow-circle-left"></i></span>


                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-8">
                        <div class="huge">@ViewBag.Archived</div>
                        <div>الطلبات المؤرشفة</div>
                    </div>
                    <div class="col-xs-2">
                        <i class="fa fa-tasks fa-3x"></i>
                    </div>

                </div>
            </div>
            <a href="@Url.Action("Order",new {state=OrderStates.complete.ToString()})">
                <div class="panel-footer">
                    <span class="pull-right">عرض التفاصيل</span>
                    <span class="pull-left"><i class="fa fa-arrow-circle-left"></i></span>


                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>