EShop.WEB/Controllers/ManageSizeAttributesController.cs
using AutoMapper;
using EShop.BLL.DTO;
using EShop.BLL.Infrastructure;
using EShop.BLL.Interfaces;
using EShop.Common;
using EShop.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace EShop.WEB.Controllers
{
    [Authorize(Roles = "AdminRole")]
    public class ManageSizeAttributesController : BaseController
    {
        private IManageSizeAttributes _manageSizeAttributeService;
        private IProductManagerService _manageProductService;
        public ManageSizeAttributesController(IManageSizeAttributes _manageSizeAttributeService, IProductManagerService _manageProductService)
        {
            this._manageSizeAttributeService = _manageSizeAttributeService;
            this._manageProductService = _manageProductService;
        }

        //
        // GET: /ManageSizeAttributes/

        public ActionResult Index(String an, String en, int PageSize = PAGE_SIZE, int page = 1, Sorts sb = Sorts.IdUp, long Id = 0)
        {
            List<OptionManagerDTO> optionsDTOs = _manageProductService.GetAllOptions();
            List<SizeAttributeDTO> AttributesDTOs = _manageSizeAttributeService.Filter(an, en, Id, sb);
            //List<SizeAttributeDTO> AttributesDTOs = new List<SizeAttributeDTO>();
            SizeAttributeIndexManagerVM sizeAttributes = new SizeAttributeIndexManagerVM
            {

                SizeAttributes = AttributesDTOs.ToPagedList(page, PageSize),
                filters = new OptionFiltersDTO
                {
                    ArabicName = an,
                    EnglishName = en,
                    PageNum = page,
                    PageSize = PageSize,
                    Id = Id,
                    SortBy = sb
                }
            };
            /* Mapper.Initialize(c => c.CreateMap<OptionValueManagerDTO, OptionValueManagerVM>());
             Mapper.Initialize(c => c.CreateMap<OptionManagerDTO, OptionManagerVM>().ForMember(dest => dest.OptionValues, opt =>
            opt.MapFrom(src => Mapper.Map<List<OptionValueManagerDTO>, List<OptionValueManagerVM>>(src.OptionValues))));

             List<OptionManagerVM> options = Mapper.Map<List<OptionManagerDTO>, List<OptionManagerVM>>(optionsDTOs);*/

            return View(sizeAttributes);
        }

        [HttpPost]
        public ActionResult Index(String an, String en, int PageSize = PAGE_SIZE,  long Id = 0,int page = 1, Sorts sb = Sorts.IdUp)
        {
            List<OptionManagerDTO> optionsDTOs = _manageProductService.GetAllOptions();
            List<SizeAttributeDTO> AttributesDTOs = _manageSizeAttributeService.Filter(an, en, Id, sb);
           // List<SizeAttributeDTO> AttributesDTOs = new List<SizeAttributeDTO>();
            SizeAttributeIndexManagerVM sizeAttributes = new SizeAttributeIndexManagerVM
            {

                SizeAttributes = AttributesDTOs.ToPagedList(page, PageSize),
                filters = new OptionFiltersDTO
                {
                    ArabicName = an,
                    EnglishName = en,
                    PageNum = page,
                    PageSize = PageSize,
                    Id = Id,
                    SortBy = sb
                }
            };
            /* Mapper.Initialize(c => c.CreateMap<OptionValueManagerDTO, OptionValueManagerVM>());
             Mapper.Initialize(c => c.CreateMap<OptionManagerDTO, OptionManagerVM>().ForMember(dest => dest.OptionValues, opt =>
            opt.MapFrom(src => Mapper.Map<List<OptionValueManagerDTO>, List<OptionValueManagerVM>>(src.OptionValues))));

             List<OptionManagerVM> options = Mapper.Map<List<OptionManagerDTO>, List<OptionManagerVM>>(optionsDTOs);*/

            return View(sizeAttributes);
        }

        [HttpPost]
        public JsonResult GetSizesForSizeCategory(long Id)
        {
            List<OptionValueManagerDTO> dto = _manageProductService.GetOptionValuesByOptionId(Id);
            SelectList sizes = new SelectList(dto, "Id", "ArabicName", 0);
            return Json(sizes);
        }

        public ActionResult Add()
        {

            AddSizeAttributeDTO addSizeAttributeDto = _manageSizeAttributeService.GetAllSizesToAddSizeAttribute();

            Mapper.Initialize(c => c.CreateMap<AddSizeAttributeDTO, AddSizeAttributeVM>());

            AddSizeAttributeVM vm = Mapper.Map<AddSizeAttributeDTO, AddSizeAttributeVM>(addSizeAttributeDto);
            //AddSizeAttributeVM vm = new AddSizeAttributeVM();
            return View(vm);
            
        }

        [HttpPost]
        public ActionResult Add(string arabicName, string englishName, long SizeCategoryId)
        {
        //    Mapper.Initialize(c => c.CreateMap<SizeAttributeValueVM, SizeAttributeValueDTO>());

        //    SizeAttributeValueDTO addSizeAttributeDto = Mapper.Map<SizeAttributeValueVM, SizeAttributeValueDTO>(sizeAttribute);
            OperationDetails op = _manageSizeAttributeService.AddSizeAttribute(arabicName, englishName, SizeCategoryId);
            return Json(new { Succedeed = op.Succedeed, message = op.Message, prop = op.Property });
            //return Json(new { Succedeed = "", message = "", prop = "" });
        }

        [HttpPost]
        public ActionResult AddSizeAttributeValue(SizeAttributeValueVM optionValue)
        {
            //Mapper.Initialize(c => c.CreateMap<SizeAttributeValueVM, SizeAttributeValueDTO>());
            //SizeAttributeValueDTO optionValueDto = Mapper.Map<SizeAttributeValueVM, SizeAttributeValueDTO>(optionValue);

            //OperationDetails op = _manageSizeAttributeService.AddSizeAttributeValue(optionValueDto);

            //List<SizeAttributeValueDTO> resultDtos = _manageSizeAttributeService.GetSizeAttributeValuesBySizeAttributeId(optionValue.SizeAttributeId);

            //AddSizeAttributeDTO addSizeAttributeDto = _manageSizeAttributeService.GetAllSizesToAddSizeAttribute();

            //Mapper.Initialize(c => c.CreateMap<AddSizeAttributeDTO, AddSizeAttributeVM>());

            //AddSizeAttributeVM vm = Mapper.Map<AddSizeAttributeDTO, AddSizeAttributeVM>(addSizeAttributeDto);

            //vm.SizeAttributeValues = resultDtos;

            //return PartialView("_AddSizeAttributeValue", vm);
            return View();
        }

        public ActionResult Edit(long Id)
        {

            AddSizeAttributeDTO addSizeAttributeDto = _manageSizeAttributeService.GetSizeAttributeById(Id);

            Mapper.Initialize(c => c.CreateMap<AddSizeAttributeDTO, AddSizeAttributeVM>());

            AddSizeAttributeVM vm = Mapper.Map<AddSizeAttributeDTO, AddSizeAttributeVM>(addSizeAttributeDto);
          
            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(string arabicName, string englishName, long Id, long SizeCategoryId)
        {
            //Mapper.Initialize(c => c.CreateMap<SizeAttributeValueVM, SizeAttributeValueDTO>());

            //SizeAttributeValueDTO addSizeAttributeDto = Mapper.Map<SizeAttributeValueVM, SizeAttributeValueDTO>(sizeAttribute);
            OperationDetails op = _manageSizeAttributeService.EditSizeAttribute(arabicName, englishName, Id, SizeCategoryId);
            return Json(new { Succedeed = op.Succedeed, message = op.Message, prop = op.Property });

        }

        [HttpPost]
        public ActionResult EditSizeAttributeValue(SizeAttributeValueVM optionValue)
        {
            Mapper.Initialize(c => c.CreateMap<SizeAttributeValueVM, SizeAttributeValueDTO>());
            SizeAttributeValueDTO optionValueDto = Mapper.Map<SizeAttributeValueVM, SizeAttributeValueDTO>(optionValue);

            //OperationDetails op = _manageSizeAttributeService.EditSizeAttributeValue(optionValueDto);

            //return Json(new { Succedeed = op.Succedeed, message = op.Message, prop = op.Property });
            return Json(new { Succedeed = "", message = "", prop = "" });

        }
        [HttpPost]
        public ActionResult Delete(long Id)
        {
            OperationDetails op = _manageSizeAttributeService.DeleteSizeAttribute(Id);
            return Json(new { Succedeed = op.Succedeed, message = op.Message, prop = op.Property });
        }
    }
}

EShop.WEB/Views/ManageSizeAttributes/Add.cshtml
@model EShop.WEB.Models.AddSizeAttributeVM
@{
    ViewBag.Title = "إضافة واصفة قياس";
    
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="content">
    <div class="page-header">
        <div class="container-fluid">
            <div class="pull-left">

                <a href="#" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
            </div>
            <h1>واصفات القياسات</h1>
            <ul class="breadcrumb">
                <li><a href="@Url.Action("Index","DashBoard")">الرئيسية</a></li>
                <li><a href="@Url.Action("Index","ManageSizeAttributes")">إضافة واصفة قياس</a></li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-pencil"></i> إضافة واصفة قياس</h3>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data" id="form-option" class="form-horizontal">
                    @Html.ValidationSummary("يرجى تصحيح الاخطاء التالية:")
                    <div class="form-group required">

                        <div class="col-sm-10">
                            <label class="col-sm-2 control-label">الاسم العربي</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <img src="~/Assets/images/flag-arabic.jpg" />
                                </span>
                                <input id="op-arabic" type="text" name="arabicName" value="" placeholder="الاسم العربي" class="form-control">
                            </div>
                        </div>

                        <div class="col-sm-10">
                            <label class="col-sm-2 control-label">الاسم الانكليزي</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <img src="~/Assets/images/flag-english.jpg" />
                                </span>
                                <input id="op-english" type="text" name="englishName" value="" placeholder="English Name" class="form-control">
                            </div>
                        </div>
                        <div class="col-sm-10">
                            <label class="col-sm-2 control-label">فئة القياسات</label>
                            <div class="input-group">
                                <select class="form-control" id="size-cat-list" name="SizeCategoryId">
                                    <option value="0">أختر فئة القياسات</option>
                                    @foreach (var SizeCategory in Model.SizesCategories)
                                    {
                                        <option value="@SizeCategory.Id">@SizeCategory.ArabicName</option>
                                    }
                                </select>
                            </div>
                        </div>
                        </div>
                    <button id="btn-save-option" form="form-option" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="Save"><i class="fa fa-save"></i></button>
                </form>
                @*<input id="optionIdTemp" type="hidden" name="optionId" value="" />*@
                <div id="option-val">
                    <form id="option-value-form" action="@Url.Action("AddSizeAttributeValue", "ManageSizeAttributes")" method="post">
                        <input id="optionId" type="hidden" name="SizeAttributeId" value="" />
                        <div id="values-div">
                            @*@{
                                Html.RenderPartial("_AddSizeAttributeValue", Model);
                            }*@
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#option-value').addClass('hidden');
            $('#btn-save-option').on('click', function (e) {
                e.preventDefault();
                var form = $("#form-option");
                //form.validate({
                //    ignore: ":hidden"
                //});
                if (form.valid() == false) {
                    generateFlash('error', "يرجى التحقق من القيم المدخلة أو ادخال الحقول المطلوبة");
                    return;
                }
                $.ajax({
                    url: '@Url.Action("Add","ManageSizeAttributes")',
                    method: 'post',
                    global:false,
                    data: $('#form-option').serialize(),
                    success: function (data) {
                        if (data.Succedeed == true) {
                            generateFlash('success', data.message);
                            $('#optionId').val(data.prop);
                           
                            
                        }
                        else {
                            generateFlash('error', data.message);
                        }
                    }
                });
            });
        });
    </script>
</div>

EShop.WEB/Views/ManageSizeAttributes/Edit.cshtml
@model EShop.WEB.Models.AddSizeAttributeVM
@{
    ViewBag.Title = "تعديل واصفة قياس";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="content">
    <div class="page-header">
        <div class="container-fluid">
            <div class="pull-left">

                <a href="@Url.Action("Index","manageSizeAttributes")" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
            </div>
            <h1>واصفات القياسات</h1>
            <ul class="breadcrumb">
                <li><a href="@Url.Action("Index","DashBoard")">الرئيسية</a></li>
                <li><a href="@Url.Action("Index","manageSizeAttributes")">واصفات القياسات</a></li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-pencil"></i> تعديل واصفة قياس</h3>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data" id="form-option" class="form-horizontal">
                    @Html.ValidationSummary("يرجى تصحيح الاخطاء التالية:")
                    <div class="form-group required">
                        <input id="size-attr-id" type="hidden" name="Id" value="@Model.SizeAttribute.Id" />
                        <div class="col-sm-10">
                            <label class="col-sm-2 control-label">الاسم العربي</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <img src="~/Assets/images/flag-arabic.jpg" />
                                </span>
                                <input id="op-arabic" type="text" name="arabicName" value="@Model.SizeAttribute.ArabicName" placeholder="الاسم العربي" class="form-control">
                            </div>
                        </div>

                        <div class="col-sm-10">
                            <label class="col-sm-2 control-label">الاسم الانكليزي</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <img src="~/Assets/images/flag-english.jpg" />
                                </span>
                                <input id="op-english" type="text" name="englishName" value="@Model.SizeAttribute.EnglishName" placeholder="English Name" class="form-control">
                            </div>
                        </div>
                        <div class="col-sm-10">
                            <label class="col-sm-2 control-label">فئة القياسات</label>
                            <div class="input-group">
                                <select class="form-control" id="size-cat-list" name="SizeCategoryId">
                                    <option value="0">أختر فئة القياسات</option>
                                    @foreach (var SizeCategory in Model.SizesCategories)
                                    {
                                        <option value="@SizeCategory.Id" @(@Model.SizeAttribute.SizeCategoryId==SizeCategory.Id?"selected":"")>@SizeCategory.ArabicName</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    <button id="btn-save-option" form="form-option" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="Save"><i class="fa fa-save"></i></button>
                </form>
                @*<input id="optionIdTemp" type="hidden" name="optionId" value="" />*@
                <div id="option-val">
                    @*<form id="option-value-form" action="@Url.Action("EditSizeAttributeValue", "ManageSizeAttributes")" method="post">
                        <input id="optionId" type="hidden" name="SizeAttributeId" value="" />
                        <div id="values-div">
                            @{
                                    Html.RenderPartial("_AddSizeAttributeValue", Model);
                                }
                        </div>
                    </form>*@

                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
           // $('#option-value').addClass('hidden');
            $('#btn-save-option').on('click', function (e) {
                e.preventDefault();
                var form = $("#form-option");
                //form.validate({
                //    ignore: ":hidden"
                //});
                if (form.valid() == false) {
                    generateFlash('error', "يرجى التحقق من القيم المدخلة أو ادخال الحقول المطلوبة");
                    return;
                }
                $.ajax({
                    url: '@Url.Action("Edit","ManageSizeAttributes")',
                    method: 'post',
                    global: false,
                    data: $('#form-option').serialize(),
                    success: function (data) {
                        if (data.Succedeed == true) {
                            generateFlash('success', data.message);
                            $('#optionId').val(data.prop);


                        }
                        else {
                            generateFlash('error', data.message);
                        }
                    }
                });
            });
        });
    </script>
</div>

EShop.WEB/Views/ManageSizeAttributes/_AddSizeAttributeValue.cshtml
@model EShop.WEB.Models.AddSizeAttributeVM

<table id="option-value" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <td class="text-center">مجموعة القياسات</td>
            <td class="text-center">القياسات</td>
            <td class="text-center">القيمة مقدرة بالـسنتيمتر</td>
            <td class="text-center"></td>

        </tr>
    </thead>
    <tbody>
        
        @foreach (var optionValue in Model.SizeAttributeValues)
        {
            <tr>
                <td class="text-center">
                    @*<label class="col-sm-2 control-label">الاسم العربي</label>*@
                    <div class="input-group">
                        @*<span class="input-group-addon">
                            <img src="~/Assets/images/flag-arabic.jpg" />
                        </span>*@
                     
                    
                        <input id="op-arabic" type="text" name="" value="@optionValue.SizeCategoryName" placeholder="" class="form-control" disabled>
                     
                    </div>
                    @*<label class="col-sm-2 control-label">الاسم الانكليزي</label>*@
                    @*<div class="input-group">
                        <span class="input-group-addon">
                            <img src="~/Assets/images/flag-english.jpg" />
                        </span>
                        <input id="op-english" type="text" name="EnglishName" value="@optionValue.EnglishName" placeholder="English Name" class="form-control" disabled>
                    </div>*@
                </td>
                <td class="text-center">
                    @*<label class="col-sm-2 control-label">الاسم العربي</label>*@
                    <div class="input-group">
                        @*<span class="input-group-addon">
                    <img src="~/Assets/images/flag-arabic.jpg" />
                </span>*@


                        <input id="op-arabic" type="text" name="" value="@optionValue.SizeValueName" placeholder="" class="form-control" disabled>

                    </div>
                    @*<label class="col-sm-2 control-label">الاسم الانكليزي</label>*@
                    @*<div class="input-group">
                <span class="input-group-addon">
                    <img src="~/Assets/images/flag-english.jpg" />
                </span>
                <input id="op-english" type="text" name="EnglishName" value="@optionValue.EnglishName" placeholder="English Name" class="form-control" disabled>
            </div>*@
                </td>
                <td class="text-center">@optionValue.Value</td>
                <td class="text-center"></td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr id="option-value-row1">
            <td class="text-center">
                @*<input type="hidden" name="option_value[1][option_value_id]" value="">*@
                <div class="input-group">
                    @*<span class="input-group-addon">
                        <img src="~/Assets/images/flag-arabic.jpg" />

                    </span>*@
                    <select class="form-control" id="size-cat-list" name="SizeCategoryId">
                        <option value="0">أختر فئة القياسات</option>
                        @foreach (var SizeCategory in Model.SizesCategories)
                        {
                            <option value="@SizeCategory.Id">@SizeCategory.ArabicName</option>
                        }
                    </select>
                            </div>
                @*<input type="hidden" name="option_value[1][option_value_id]" value="">*@

                @*<div class="input-group">
                    <span class="input-group-addon">
                        <img src="~/Assets/images/flag-english.jpg" />
                    </span>
                    <input type="text" name="EnglishName" value="" placeholder="English Name" class="form-control">
                </div>*@
            </td>
            <td class="text-center">
                @*<input type="hidden" name="option_value[1][option_value_id]" value="">*@
                <div class="input-group">
                    @*<span class="input-group-addon">
                    <img src="~/Assets/images/flag-arabic.jpg" />

                </span>*@
                    <select class="form-control" id="size-val-list" name="SizeValueId"></select>
                    
                </div>
                @*<input type="hidden" name="option_value[1][option_value_id]" value="">*@

                @*<div class="input-group">
                <span class="input-group-addon">
                    <img src="~/Assets/images/flag-english.jpg" />
                </span>
                <input type="text" name="EnglishName" value="" placeholder="English Name" class="form-control">
            </div>*@
            </td>
            <td class="text-right">
                <input type="text" name="Value" value="" placeholder="القيمة" class="form-control">

            </td>
            <td class="text-left">
                <button id="add-op-value" type="button" data-toggle="tooltip" title="إضافة" class="btn btn-danger">
                    <i class="fa fa-minus-circle">
                    </i>
                </button>
            </td>
        </tr>
    </tfoot>
</table>

<script>
    $(document).ready(function () {
        $('#size-cat-list').on('change', function () {
            var procemessage = "<option value='0'> Please wait...</option>";
            $("#size-val-list").html(procemessage).show();
            var url = '@Url.Action("GetSizesForSizeCategory", "ManageSizeAttributes")';
            var sizeCatId = $(this).val();
            $.ajax({
                url: url,
                data: { Id: sizeCatId },
                cache: false,
                type: "POST",
                success: function (data) {
                    var markup = "<option value='0'>اختر القياس</option>";
                    for (var x = 0; x < data.length; x++) {
                        markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                    }
                    $("#size-val-list").html(markup).show();
                },
                error: function (reponse) {
                    alert("error : " + reponse);
                }
            });

        });

        $('#add-op-value').on('click', function (e) {
            e.preventDefault();
           // $('#option-value-form').submit();
            $.ajax({
                url: '@Url.Action("AddSizeAttributeValue", "ManageSizeAttributes")',
                method: 'post',
                data: $('#option-value-form').serialize(),
                success: function (data) {
                    console.log(data);
                    $('#values-div').html(data);

                }
            });
        });
    });
</script>